//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal__RyN__.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleado
    {

        [Display(Name = "Empleado")]
        public int Id_Empleado { get; set; }

        [Display(Name = "Codigo")]
        [Required(ErrorMessage = "Campo obligatorio")]
        [StringLength(4)]
        public string Codigo_Empleado { get; set; }

        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Campo obligatorio")]
        [StringLength(50)]
        public string Nombre_Empleado { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [StringLength(50)]
        public string Apellido { get; set; }

        [DataType(DataType.PhoneNumber)]
        [StringLength(10)]
        public string Telefono { get; set; }


        public Nullable<int> Id_Depto { get; set; }
        public Nullable<int> Id_Cargo { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]

        [Display(Name = "Fecha de ingreso")]
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<decimal> Salario { get; set; }

        [Display(Name ="Activo")]
        public bool Status { get; set; }

        //Aqui debajo debes agregar un public para departamento(Parecido al de cargo)
        
        public Departamento Departamento { get; set; }

       //Metodo Cargo 
        
        public Cargo Cargo { get; set; }
        public List<Licencia> Licencias { get; set; }
        public List<Permiso> Permisos { get; set; }
        public List<Vacaciones> Vacaciones { get; set; }
        
    }
}
