//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal__RyN__.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleado
    {
        public int Id_Empleado { get; set; }
        public string Codigo_Empleado { get; set; }
        public string Nombre_Empleado { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Id_Depto { get; set; }
        public Nullable<int> Id_Cargo { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public bool Status { get; set; }

        //Aqui debajo debes agregar un public para departamento(Parecido al de cargo)
        

       //Metodo Cargo 
        public Cargo Cargo { get; set; }
        public List<Licencia> Licencias { get; set; }
        public List<Permiso> Permisos { get; set; }
       
        public List<Vacaciones> Vacaciones { get; set; }
    }
}
