//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal__RyN__.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vacaciones
    {
        
        public int Id_vacaciones { get; set; }
        [Required]
        [Display(Name = "Empleado")]
        public Nullable<int> Id_Empleado { get; set; }

        [Required]
        [Display(Name = "Inicio de Vacaciones")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Inicio_Vacaciones { get; set; }

        [Required]
        [Display(Name = "Fin de Vacaciones")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fin_Vacaciones { get; set; }
        public Nullable<int> Año { get; set; }
        public string Comentario { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
